config/routes.rb
Rails.application.routes.draw do
  resources :cands
  root 'home#index'
  get 'home/index'
  get 'home/repair'
  post 'cands/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cand.rb
class Cand < ApplicationRecord
end

app/controllers/cands_controller.rb
$password = 'dayday123'
class CandsController < ApplicationController
  before_action :set_cand, only: [:show, :edit, :update, :destroy]

  # GET /cands
  # GET /cands.json
  def index
    @cands = Cand.all
  end

  # GET /cands/1
  # GET /cands/1.json
  def show
  end

  # GET /cands/new
  def new
    @cand = Cand.new
  end

  # GET /cands/1/edit
  def edit
  end

  # POST /cands
  # POST /cands.json
  def create
    @cand = Cand.new(cand_params)
    @cand = Cand.new(cand_params)
        respond_to do |format|
          if @cand.pwd == $password
            if @cand.save
              format.html { redirect_to @cand, notice: 'Cand was successfully created.' }
              format.json { render :show, status: :created, location: @cand }
              @cand.pwd = "re"
            else
              format.html { render :new }
              format.json { render json: @cand.errors, status: :unprocessable_entity }
            end
          else
            format.html {render :new, notice: 'no'}
            format.json { render json: @cand.errors, status: :unprocessable_entity }
            @cand.pwd = "re"
          end
        end
  end

  # PATCH/PUT /cands/1
  # PATCH/PUT /cands/1.json
  def update
    respond_to do |format|
          if @cand.update(cand_params)
            if @cand.pwd == $password
            format.html { redirect_to @cand, notice: 'Cand was successfully updated.' }
            format.json { render :show, status: :ok, location: @cand }
          else
            format.html {render :edit, notice: 'no'}
            format.json { render json: @cand.errors, status: :unprocessable_entity }
          end
          else
            format.html { render :edit }
            format.json { render json: @cand.errors, status: :unprocessable_entity }
          end
      end
  end

  # DELETE /cands/1
  # DELETE /cands/1.json
  def destroy
    if params[:pwd] == $password
        @cand.destroy
        respond_to do |format|
          format.html { redirect_to cands_url, notice: 'Cand was successfully destroyed.' }
          format.json { head :no_content }
        end
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cand
      @cand = Cand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cand_params
      params.require(:cand).permit(:name, :date, :beginc, :endc, :act, :loca, :pwd)
    end
end

app/helpers/cands_helper.rb
module CandsHelper
end

app/views/cands/_form.html.erb
<%= form_for(cand) do |f| %>
  <% if cand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cand.errors.count, "error") %> prohibited this cand from being saved:</h2>

      <ul>
      <% cand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.text_field :date %>
  </div>

  <div class="field">
    <%= f.label :beginc %>
    <%= f.number_field :beginc %>
  </div>

  <div class="field">
    <%= f.label :endc %>
    <%= f.number_field :endc %>
  </div>

  <div class="field">
    <%= f.label :act %>
    <%= f.text_area :act %>
  </div>

  <div class="field">
    <%= f.label :loca %>
    <%= f.text_field :loca %>
  </div>

  <div class="field">
    <%= f.label :pwd %>
    <input type="password"
    <%= f.text_field :pwd %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cands/edit.html.erb
<h1>Editing Cand</h1>
<% @cand.pwd = "re"%>
<%= render 'form', cand: @cand %>

<%= link_to 'Show', @cand %> |
<%= link_to 'Back', cands_path %>

app/views/cands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cands</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Beginc</th>
      <th>Endc</th>
      <th>Act</th>
      <th>Loca</th>
      <th>Pwd</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cands.each do |cand| %>
      <tr>
        <td><%= cand.name %></td>
        <td><%= cand.date %></td>
        <td><%= cand.beginc %></td>
        <td><%= cand.endc %></td>
        <td><%= cand.act %></td>
        <td><%= cand.loca %></td>
        <td><%= link_to 'Show', cand %></td>
        <td><%= link_to 'Edit', edit_cand_path(cand) %></td>
        <td><%= link_to 'Destroy', cand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <form action="/cands/destroy" method="post">
          <input type="text" name ="pwd">
          <input type="hidden" name="id" value="<%= cand.id %>">
          <input type="submit" value="보내기">
        </form>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cand', new_cand_path %>

app/views/cands/new.html.erb
<h1>New Cand</h1>

<%= render 'form', cand: @cand %>

<%= link_to 'Back', cands_path %>

app/views/cands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cand.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @cand.date %>
</p>

<p>
  <strong>Beginc:</strong>
  <%= @cand.beginc %>
</p>

<p>
  <strong>Endc:</strong>
  <%= @cand.endc %>
</p>

<p>
  <strong>Act:</strong>
  <%= @cand.act %>
</p>

<p>
  <strong>Loca:</strong>
  <%= @cand.loca %>
</p>

<p>
  <strong>Pwd:</strong>
  password
</p>

<%= link_to 'Edit', edit_cand_path(@cand) %> |
<%= link_to 'Back', cands_path %> | 
<%= link_to "Show", new_cand_path(@cand) %>